### ISSUE TITLE
Application aborts with `unknown color name "systemWindowBackgroundColor"`

### ISSUE THREAD

**Issue by ghost** [Zitronenjoghurt/Colonaut#3]
Application refused starting with the following traceback:
```
Traceback (most recent call last):
  File "[...]\Colonaut\main.py", line 3, in <module>
    gm = GameManager.get_instance()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Colonaut\src\classes\game_manager.py", line 31, in get_instance
    GameManager._instance = GameManager()
                            ^^^^^^^^^^^^^
  File "[...]\Colonaut\src\classes\game_manager.py", line 18, in __init__
    self.ui_system = UISystem()
                     ^^^^^^^^^^
  File "[...]\Colonaut\src\ui\ui_system.py", line 23, in __init__
    self.screens["planet_view"] = Screens.PlanetViewScreen(self)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Colonaut\src\ui\screens\planet_view.py", line 30, in __init__
    self.system_console = Components.ShipConsole(self)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Colonaut\src\ui\components\ship_console.py", line 18, in __init__
    self.button_frame = ctk.CTkFrame(self, bg_color='systemWindowBackgroundColor')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]\Colonaut\venv\Lib\site-packages\customtkinter\windows\widgets\ctk_frame.py", line 33, in __init__
    super().__init__(master=master, bg_color=bg_color, width=width, height=height, **kwargs)
  File "[...]\Colonaut\venv\Lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 68, in __init__
    super().configure(bg=self._apply_appearance_mode(self._bg_color))
  File "C:\Program Files\Python\3.12.0\Lib\tkinter\__init__.py", line 1716, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\3.12.0\Lib\tkinter\__init__.py", line 1706, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "systemWindowBackgroundColor"
```

OS: `Windows 10`
Python: `3.12.0`
Fresh (synced) installation of the requirements into a virtual environment.

**Comment by Zitronenjoghurt** [comment]
Thank you :) I removed the color as I only added it for testing and it didnt change anything. Forgot to remove it^^" 
https://github.com/Zitronenjoghurt/Colonaut/commit/87df402e2a83714cb958c8538f5f2347ab654c21
